apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path "/var/log/containers/*httpd*.log"
      pos_file /var/log/httpd-container.log.pos
      format json
      tag hoge
    </source>
    <match hoge>
      @type s3
      aws_key_id AKIATJJHFJFN4XWPVGU7
      aws_sec_key 0h/0WDNusDjSCFBmlX+QvUfmAMWOMN1BkS0YXb4H
      s3_bucket myk8slogbucket
      s3_region ap-northeast-1
      time_slice_format %Y%m%d%H%M
    </match>
      <buffer>
        @type file
        path /fluentd/log/s3
        timekey 60
        timekey_wait 10m
        chunk_limit_size 256m
      </buffer>