apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: 226104789339.dkr.ecr.ap-northeast-1.amazonaws.com/teas_calc:0.1
        name: guestbook-ui
        ports:
        - containerPort: 5042
